### ISSUE TITLE
Spectral Bands order

### ISSUE THREAD

**Issue by Sina-Mohammadi** [0zgur0/ms-convSTAR#1]
Hello. What is the order of the spectral bands in your data if I want to use all 9 bands? Could you please tell me each of the 9 channels (bands) you have in your data corresponds to which spectral bands? For instance, the fourth channel corresponds to NIR? SWIR?....

**Comment by 0zgur0** [comment]
bands: blue=2, green=1, red=3, NIR=0

NIR, G, B, R, B05, B06, B07, B11, B12

**Comment by Sina-Mohammadi** [comment]
So the first channel is NIR and the last channel is B12. Thanks.
Best, Sina
