### ISSUE TITLE
The problem about ZueriCrop dataset

### ISSUE THREAD

**Issue by LiuluKakali** [0zgur0/ms-convSTAR#2]
We are very interested in this dataset but have some confusion for this dataset.  
  In this paper, I learned that the input image sizes are H = W = 24, B = 4 and sequence length is T = 71.  But the size of "data" in the dataset is (27977,142,24,24,9). I am very confused about the time dimension (Second dimension). Why is not72 but is 142.

We look forward to your reply.

**Comment by 0zgur0** [comment]
we subsample in the time direction (1/2) for the experiments in the paper since we did not see a significant performance difference but increased computation.
