### ISSUE TITLE
52 Classes instead of 48

### ISSUE THREAD

**Issue by Sina-Mohammadi** [0zgur0/ms-convSTAR#3]
Hello. When I generate the data using your data loader, the label is indexed from 0 to 51, which is different from what has been mentioned in your paper. I investigated your code and I realized that the labels 0, 47, 25, and 35 belong to "0_unkown", "Waters", "Non agriculture", and "Special cultures" respectively. These classes are not among those 48 classes in the paper. To my understanding, to obtain the 48 classes mentioned in the paper, I should remove the labels 0, 47, 25, and 35 (and their corresponding pixels) from the data. Am I correct? Could you please confirm that?

**Comment by 0zgur0** [comment]
it is true.
